name: Release Snapshot

on:
  push:
    branches:
      - canary
      - canary-*
      - canary/*
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: changeset version
        run: yarn changeset version --snapshot canary

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: yarn changeset publish --no-git-tag --tag canary

      - name: Delete Branch
        if: contains(github.ref, 'canary')
        run: |
          branch=${GITHUB_REF#refs/heads/}
          git push origin --delete $branch
